# Test python script to interact with Plantronics SDK
# Lewis.Collins@Plantronics.com 21st Aug 2014
#
# Pre-requisites:
# --
# 1. http://www.plantronics.com/software
#    - download Latest Hub for Windows
#
# 2. https://www.python.org/downloads/
#    - download and install Python 3.4.1 for Windows 64-bit or 32-bit
#
# 3. www.lfd.uci.edu/~gohlke/pythonlibs/#pythonnet
#    - download and run installer: 64-bit: pythonnet-2.0.0.win-amd64-py3.4.exe, 32-bit: pythonnet-2.0.0.win32-py3.4.exe
#     (this is the Python for .NET module)
#
# 4. PLTLayer.dll
#    - The Minimalist Plantronics .NET API - download from Developer City on Wave
#
# **NOTE**: ensure you match system architectures 64-bit or 32-bit!!!
# The "python" and "Python for .NET" must match, also the .NET Assembly must
# target same CPU: for 64-bit should target "x64 or Any", and for 32-bit should target "x86"
#
# More info:
# --
# http://pythonnet.sourceforge.net/readme.html#getting_started
# - this is the reference guide for Python for .NET
#
# How to run:
# --
#   Once you have the above pre-requisites installed:
#   From Command Prompt type:
#
#		python pltlayerdemo.py
#
# Have fun! ;-)
#

import msvcrt
import clr
import time
pltlayer = clr.AddReference("PLTLayer")

from System import String, Int32
from System.Collections.Generic import List
p = String("Welcome to PLTLayer test")		# test that .NET is working
print (p)

print (pltlayer.FullName)

from Plantronics.EZ.API import PLTLayer

# 1. Setup Plantronics
plt = PLTLayer.Instance
quit = False

def handler(source, args):
	print ('PltEvent Occured! EventType=', args.EventType, '(' , args.EventTypeStr , ')')
	if args.MyParams is not None:
		for item in args.MyParams:
			print (item)
	
plt.PltEvent += handler

plt.setup("PLTLayerPythonTest")

# 2. Main application loop
def GetUserInput(prompt = "Enter Command (or type help) > "):
	print
	var = input(prompt)
	return var

def ShowValidCommands():
	print
	print ("Valid commands:")
	print ("--")
	print ("on, ring, ans, off, muteon, muteoff, hold, resume, lineon, lineoff,\r\nlinehold, lineresume, dialmob, ansmob, rejmob, endmob, getgenes, help, quit")

def safe_cast(val, to_type, default=None):
    try:
        return to_type(val)
    except ValueError:
        return default
		
def ReadCallInfo():
	isincoming = safe_cast(GetUserInput("Enter call direction \r\n(integer, 1 = incoming, 2 = outgoing) : "),int,1) != 2
	callid = safe_cast(GetUserInput("Enter call id (integer)\r\nor press Enter to generate call id automatically : "),int,-1)
	contactname = GetUserInput("Enter contact name (string)\r\nor press Enter to skip : ")
	return isincoming, callid, contactname
	
#WORK IN PROGRESS!!! - TODO port remaining commands from C# sample!
def NextUserCommand():
	command = GetUserInput()
	isincoming = True
	callid = 0
	contactname = ""
	line = 0
	numbertodial = ""
	global quit
	if command == "on":
		isincoming, callid, contactname = ReadCallInfo()
		# Notify Plantronics our app has a new incoming or outgoing call
		if callid == -1:
			# generate a call id automatically
			if len(contactname)>0:
				callid = plt.on(isincoming, contactname)
			else:
				callid = plt.on(isincoming)
			print ("\r\nAutogenerated call id was: ", callid)
		else:
			# use the call id specified by our app
			plt.on(isincoming, callid, contactname)
	elif command == "quit":
		quit = True
	elif command == "help":
		ShowValidCommands()
	else:
		print ("unknown command")
		ShowValidCommands()
	return

while (quit is not True):
	NextUserCommand()

time.sleep(1)	 #wait for 1 second, *warning* without this Hub will crash!

# 3. Shutdown Plantronics
plt.PltEvent -= handler
plt.shutdown()
print ("Bye")
